Changes in typed signature validation and normalization
MetaMask/eth-json-rpc-middleware pull request #318
Opened 2024-07-18 15:42 UTC by jpuri

The PR addresses these 2 issues:

https://github.com/MetaMask/metamask-extension/issues/25733
https://github.com/MetaMask/MetaMask-planning/issues/2810

2024-07-18 15:44 UTC, jpuri commented on src/utils/normalize.ts
>    }
Normilizing decimal and octal value is removed now, only normalization now is replacing `0X` prefix with `0x`.

2024-07-18 16:13 UTC, mcmire submitted a review, later dismissed
LGTM!

2024-07-18 16:17 UTC, mcmire commented
Oof, I see that CI is failing. This could be either a problem where the cache is not being properly restored, or the incorrect set of files is being saved in the cache. In other repos we've discussed replacing `yarn --immutable --immutable-cache` with `yarn --immutable` in `.github/workflows/build-lint-test.yml`. I'll try to investigate soon, but you could experimenting with that if you're stuck.

2024-07-19 14:25 UTC, cryptodev-2s commented
> > Oof, I see that CI is failing. This could be either a problem where the cache is not being properly restored, or the incorrect set of files is being saved in the cache. In other repos we've discussed replacing `yarn --immutable --immutable-cache` with `yarn --immutable` in `.github/workflows/build-lint-test.yml`. I'll try to investigate soon, but you could experimenting with that if you're stuck.
> 
> Saw this in other repos when rerunning previously passing jobs. Also specifically Node 22.
> 
> Node.js 22.5.0 was just released so maybe something [lurking here](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.5.0)?
> 
> Unless it's simply an intermittent infra issue at GH.



> > Oof, I see that CI is failing. This could be either a problem where the cache is not being properly restored, or the incorrect set of files is being saved in the cache. In other repos we've discussed replacing `yarn --immutable --immutable-cache` with `yarn --immutable` in `.github/workflows/build-lint-test.yml`. I'll try to investigate soon, but you could experimenting with that if you're stuck.
> 
> Saw this in other repos when rerunning previously passing jobs. Also specifically Node 22.
> 
> Node.js 22.5.0 was just released so maybe something [lurking here](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.5.0)?
> 
> Unless it's simply an intermittent infra issue at GH.

@legobeat a fix for this has just been included in a new node patch [`v22.5.1`](https://github.com/nodejs/node/pull/53935)

2024-07-19 20:11 UTC, mcmire commented
I've fixed the Node issue here: https://github.com/MetaMask/eth-json-rpc-middleware/pull/321

2024-07-20 02:45 UTC, matthewwalsh0 submitted a review, later dismissed

2024-07-22 10:17 UTC, OGPoyraz approved these changes

2024-07-23 17:48 UTC, mcmire submitted a review, later dismissed
Looks good!

2024-07-23 19:51 UTC, cryptodev-2s requested changes

2024-07-23 19:51 UTC, cryptodev-2s commented on .github/workflows/build-lint-test.yml
> -      - run: yarn --immutable --immutable-cache
Can we rollback this change ?

2024-07-23 23:24 UTC, jpuri commented on .github/workflows/build-lint-test.yml
> -      - run: yarn --immutable --immutable-cache
👍 I updated the PR

2024-07-23 23:25 UTC, cryptodev-2s approved these changes
LGTM!

2024-07-23 23:26 UTC, merged